#!/bin/bash
set -e

# Dreamhost deployment script for Family Photo Album
# Run from within the family-photo-album directory

# Color output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

CONFIG_FILE=".deploy-config"

echo -e "${YELLOW}🚀 Starting Dreamhost deployment...${NC}"

# Check if we're in the right directory
if [ ! -f "composer.json" ] || [ ! -f "artisan" ]; then
    echo -e "${RED}❌ Please run this script from the family-photo-album directory${NC}"
    exit 1
fi

# Load or prompt for configuration
if [ -f "$CONFIG_FILE" ]; then
    echo -e "${BLUE}📋 Loading deployment configuration...${NC}"
    source "$CONFIG_FILE"
    echo -e "${GREEN}✅ Using server: $DEPLOY_USERNAME@$DEPLOY_HOST${NC}"
else
    echo -e "${YELLOW}⚙️  First-time setup: Please enter your deployment details${NC}"
    
    read -p "Dreamhost username: " DEPLOY_USERNAME
    read -p "Dreamhost hostname (e.g., yoursite.com): " DEPLOY_HOST
    read -p "Domain directory name (e.g., yourphotosite.com): " DOMAIN_DIR
    
    # Save configuration
    cat > "$CONFIG_FILE" << EOF
# Dreamhost deployment configuration
# Generated by deploy.sh - edit as needed
DEPLOY_USERNAME="$DEPLOY_USERNAME"
DEPLOY_HOST="$DEPLOY_HOST"
DOMAIN_DIR="$DOMAIN_DIR"
EOF
    
    echo -e "${GREEN}✅ Configuration saved to $CONFIG_FILE${NC}"
fi

# Build dependencies and assets
echo -e "${YELLOW}📦 Installing Composer dependencies...${NC}"
composer install --no-dev --optimize-autoloader

echo -e "${YELLOW}🏗️  Building assets...${NC}"
npm run build

# Deploy to server
echo -e "${YELLOW}📤 Uploading to $DEPLOY_USERNAME@$DEPLOY_HOST...${NC}"

# Use rsync with specific exclusions (not .gitignore)
rsync -avz \
    --exclude='.git/' \
    --exclude='.env' \
    --exclude='.deploy-config' \
    --exclude='node_modules/' \
    --exclude='database/database.sqlite' \
    --exclude='storage/app/public/photos/' \
    --exclude='storage/framework/views/*.php' \
    --exclude='storage/framework/cache/data/*' \
    --exclude='storage/framework/sessions/*' \
    --exclude='storage/logs/*.log' \
    --exclude='tests/' \
    --exclude='.DS_Store' \
    ./ "$DEPLOY_USERNAME@$DEPLOY_HOST:~/temp-upload/"

# Upload server-specific files
echo -e "${YELLOW}📤 Uploading server-specific files...${NC}"
rsync -avz server-files/ "$DEPLOY_USERNAME@$DEPLOY_HOST:~/server-files/"

echo -e "${GREEN}✅ Upload complete!${NC}"
echo -e "${YELLOW}📋 Next steps:${NC}"
echo "   1. SSH into your server: ${BLUE}ssh $DEPLOY_USERNAME@$DEPLOY_HOST${NC}"
echo "   2. Run the update script: ${BLUE}~/update-photo-album.sh${NC}"
echo ""
echo -e "${GREEN}🎉 Deployment ready!${NC}"